name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Remplace par 'master' si c'est le nom de ta branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # ATTENTION : Modifie le --base-href selon ton cas (voir l'étape 4)
      - name: Build web
        run: flutter build web --release --base-href "/invest_app/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web